<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Pengenalan Tipe data dan Variable”**

**Disusun Oleh :**

**Harits Atha Ikhvan**

**2611533005**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji dan syukur penulis ucapkan kepada Tuhan Yang Maha Esa atas segala rahmat dan karunia-Nya, sehingga penulis dapat menyelesaikan laporan praktikum yang berjudul “Pengenalan Tipe Data dan Variabel”. Laporan ini disusun sebagai bentuk dokumentasi dari praktikum yang telah dilaksanakan serta untuk memenuhi salah satu tugas dalam kegiatan praktikum.

Melalui praktikum ini, penulis mempelajari beberapa konsep dasar dalam pemrograman Python, khususnya mengenai variabel dan tipe data. Materi yang dipraktikkan meliputi tipe data integer, float, complex, string, dan boolean, serta penggunaan input, output, operator, percabangan, dan konstanta dalam program sederhana.

Penulis menyadari bahwa laporan ini masih memiliki kekurangan, baik dari segi penyusunan maupun pembahasannya. Oleh karena itu, kritik dan saran yang bersifat membangun sangat diperlukan untuk perbaikan pada laporan berikutnya.

Akhir kata, penulis berharap laporan ini dapat memberikan manfaat dan membantu dalam memahami penerapan dasar-dasar pemrograman Python.

Padang 2026

Harits Atha Ikhvan

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Kemajuan teknologi yang terus berkembang membuat kemampuan pemrograman semakin dibutuhkan, khususnya dalam bidang teknologi informasi. Pemrograman dapat dimanfaatkan untuk membangun aplikasi sekaligus membantu menyelesaikan berbagai masalah dengan cara yang sistematis. Salah satu bahasa yang sering digunakan untuk mempelajari dasar pemrograman adalah Python. Bahasa ini memiliki penulisan kode yang relatif sederhana sehingga lebih mudah dipahami oleh pemula.

Dalam penggunaan Python, terdapat beberapa materi dasar yang perlu dipahami sebelum membuat program yang lebih kompleks. Materi tersebut meliputi variabel, tipe data, operator, input dan output, serta percabangan. Pemahaman terhadap materi tersebut diperlukan karena menjadi bagian penting dalam proses pembuatan sebuah program. Selain itu, Python juga mendukung pengolahan data numerik yang dapat digunakan untuk melakukan perhitungan dengan operator aritmatika.

Berdasarkan hal tersebut, praktikum ini dilaksanakan untuk mempelajari sekaligus menerapkan konsep dasar Python melalui beberapa contoh program. Program yang digunakan mencakup tipe data integer, float, complex, string, dan boolean, serta penerapan input, output, percabangan, dan operasi aritmatika untuk menghitung luas bangun datar. Melalui kegiatan ini, mahasiswa diharapkan dapat memahami cara kerja konsep dasar Python dan menggunakannya untuk membuat program sederhana.


## 1.2 Tujuan
1. Memahami dasar-dasar pemrograman dengan menggunakan bahasa Python.
2. Mengenal berbagai jenis tipe data yang tersedia dalam Python.
3. Memahami cara penerapan variabel, operator, input, dan output pada program.
4. Mengetahui penggunaan percabangan if serta operator logika untuk menentukan suatu kondisi.
5. Menerapkan konsep dasar Python dalam pembuatan program yang melakukan perhitungan sederhana.

## 1.3 Manfaat
1. Memperdalam pemahaman mengenai dasar pemrograman menggunakan Python.
2. Membiasakan diri dalam membuat serta menjalankan program sederhana.
3. Menambah pemahaman mengenai penggunaan tipe data dan variabel berdasarkan kebutuhan program.
4. Mengembangkan kemampuan berpikir secara logis dan teratur dalam menyelesaikan masalah melalui pemrograman.
5. Memberikan pemahaman awal yang dapat digunakan untuk mempelajari materi Python pada tingkat yang lebih lanjut.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

Python adalah salah satu bahasa pemrograman tingkat tinggi yang dikenal dengan penulisan sintaksnya yang relatif sederhana. Bahasa ini dapat dimanfaatkan untuk mengembangkan berbagai macam program, baik untuk kebutuhan dasar maupun aplikasi yang lebih kompleks. Dalam mempelajari Python, terdapat beberapa konsep utama yang perlu dipahami, di antaranya variabel, tipe data, operator, input, output, dan percabangan.

1. Variabel
Variabel digunakan untuk menyimpan sebuah nilai atau data yang nantinya dapat digunakan kembali dalam program. Pada Python, pembuatan variabel dapat dilakukan dengan langsung memberikan suatu nilai tanpa perlu mendefinisikan tipe datanya terlebih dahulu. Sebagai contoh, nilai = 85.

2. Tipe Data
Tipe data menunjukkan jenis data yang tersimpan pada sebuah variabel. Python memiliki beberapa tipe data dasar, seperti int untuk bilangan bulat, float untuk bilangan pecahan atau desimal, complex untuk bilangan kompleks, str untuk data berupa teks, serta bool untuk menyatakan kondisi benar atau salah melalui nilai True dan False.

3. Input dan Output
Input merupakan proses untuk mendapatkan data atau masukan dari pengguna. Pada Python, proses tersebut dapat dilakukan menggunakan fungsi input(). Sebaliknya, output digunakan untuk menampilkan informasi maupun hasil dari proses program dengan fungsi print(). Nilai yang diterima melalui input() pada awalnya memiliki tipe string, sehingga perlu dilakukan konversi menggunakan int() atau float() apabila data tersebut akan digunakan dalam operasi perhitungan.

4. Operator
Operator merupakan simbol yang digunakan untuk melakukan suatu operasi terhadap data. Beberapa operator aritmatika yang umum digunakan dalam Python adalah +, -, *, dan /, yang masing-masing dapat digunakan untuk melakukan perhitungan. Selain itu, terdapat operator perbandingan seperti >= yang digunakan untuk membandingkan dua nilai dan menghasilkan nilai boolean.

5. Percabangan
Percabangan berfungsi untuk menentukan perintah yang dijalankan berdasarkan kondisi tertentu. Python menyediakan pernyataan if untuk membuat percabangan. Jika terdapat lebih dari satu kondisi yang perlu diperiksa, operator logika seperti and dapat digunakan untuk menghubungkan kondisi-kondisi tersebut.

6. Konstanta
Konstanta adalah nilai yang ditetapkan untuk digunakan sebagai nilai tetap dalam suatu program. Pada Python, penggunaan Final dari modul typing dapat digunakan sebagai penanda bahwa suatu nilai ditujukan untuk tidak diubah. Contohnya adalah konstanta PI yang dapat digunakan ketika melakukan perhitungan luas lingkaran.

## 2.2 Kode Program

### 2.2.1 Program "Numerik_2611533005.py"

In [1]:
# Buat file  dengan nama Numerik_NIM.py
# nama variable ditambah 4 digit terakhir NIM contoh: a_5500
# #create a variable with numeric type value
a_3005=100
print("The type of variable having value", a_3005, " is ", type(a_3005))

#create a variable with float value
b_3005=10.2345
print("The type of variable having value", b_3005, " is ", type(b_3005))

#create a variable with complex value.
c_3005=100+3j
print("The type of variable having value", c_3005, " is ", type(c_3005))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**
1. Pada bagian pertama, program mendefinisikan variabel a_3005 dengan nilai 100. Setelah itu, program menampilkan tipe data yang dimiliki variabel tersebut. Karena nilainya berupa bilangan bulat, tipe datanya adalah integer (int).

2. Selanjutnya, variabel b_3005 diisi dengan nilai 10.2345. Program kemudian mengecek dan menampilkan tipe datanya. Nilai tersebut merupakan tipe float karena mengandung bilangan desimal.

3. Pada bagian terakhir, variabel c_3005 diberi nilai 100 + 3j. Program menampilkan tipe data dari variabel tersebut, yaitu complex, karena nilai tersebut memiliki bagian imajiner yang menggunakan simbol j.


### 2.2.2 Program "String_2611533005.py"

In [2]:
# Buat file dengan nama string_NIM.py
# nama variable ditambah 4 digit nim terakhir contoh: nama_1234
# ganti programnya dan data masing2
nama_3005 = "Harits"
jenis_kelamin_3005 = 'L'
alamat_3005 = """
    Komplek Unand
    Kec.pauh
    Kota Padang
"""
agama_3005 = 'Islam'

print("Nama saya adalah: ", nama_3005)
print("Jenis kelamin saya adalah: ", jenis_kelamin_3005)
print("Alamat saya adalah: ", alamat_3005)
print("Agama saya adalah: ", agama_3005)

Nama saya adalah:  Harits
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Komplek Unand
    Kec.pauh
    Kota Padang

Agama saya adalah:  Islam


**Penjelasan :**

1. Variabel nama_3005 digunakan untuk menyimpan informasi nama dalam bentuk teks (string), yaitu "Harits Atha Ikhvan".
2. Variabel jenis_kelamin_3005 berisi karakter "L" sebagai keterangan jenis kelamin laki-laki.
3. Variabel alamat_3005 digunakan untuk menyimpan alamat yang ditulis dalam beberapa baris. Penulisan tersebut menggunakan multiline string dengan tanda petik tiga (""").
4. Variabel agama_3005 menyimpan informasi agama dalam bentuk data teks, yaitu "Islam".
5. Selanjutnya, fungsi print() digunakan untuk menampilkan seluruh informasi yang tersimpan pada variabel nama, jenis kelamin, alamat, dan agama.


### 2.2.3 Program "Boolean_2611533005.py"

In [3]:
# Buat file dengan nama Boolean_NIM.py
# Nama variable dtambah 4 digit terakhir contoh: nilai_1234
# Deklarasi variable dengan tipe data boolean

# # Deklarasi variabel dengan tipe data Boolean
is_lulus_3005 = True
is_cumlaude_3005 = True

# Menggunakan Boolean
nilai_3005 = 85
batas_lulus_3005 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_3005 = nilai_3005 >= batas_lulus_3005 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_3005)
print("Apakah Lulus?:", status_kelulusan_3005)
if is_lulus_3005 and is_cumlaude_3005:
    print("Selamat, Anda lulus dengan predikat Cumlaude!")

=== Check Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dengan predikat Cumlaude!


**Penjelasan :**

1. Program diawali dengan memberikan nilai True pada variabel is_lulus_3005 dan is_cumlaude_3005 sebagai penanda bahwa kedua kondisi tersebut bernilai benar.
2. Selanjutnya, variabel nilai_3005 diisi dengan nilai 85, sedangkan batas_lulus_3005 ditetapkan sebesar 75 sebagai batas nilai untuk dinyatakan lulus.
3. Variabel status_kelulusan_3005 diperoleh dari hasil perbandingan antara nilai_3005 dan batas_lulus_3005. Hasilnya adalah True karena nilai 85 memenuhi kondisi lebih besar atau sama dengan 75.
4. Setelah itu, fungsi print() digunakan untuk menampilkan nilai yang diperoleh serta hasil pengecekan status kelulusan.
5. Terakhir, perintah if bersama operator and digunakan untuk memastikan kedua kondisi, yaitu lulus dan Cum Laude, terpenuhi. Karena keduanya bernilai True, program menampilkan keterangan bahwa pengguna lulus dengan predikat Cum Laude.


### 2.2.4 Program "Input_2611533005.py"

In [5]:
# Buat file dengan nama Input_NIM.py
# Buat program untuk menghitung luas persegi panjang
# Nama variable ditambah 4 digit nim terakhir contoh: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer

panjang_3005 = (input('Masukkan nilai panjang: '))
lebar_3005 = (input('Masukkan nilai lebar: '))
luas_3005 = int(panjang_3005) * int(lebar_3005)
print("Luas =", luas_3005)

Luas = 6000


**Penjelasan :**

1. Program meminta pengguna mengisi nilai panjang melalui input(), lalu data tersebut disimpan pada variabel panjang_3005.
2. Selanjutnya, pengguna diminta memasukkan nilai lebar yang kemudian disimpan dalam variabel lebar_3005.
3. Nilai panjang dan lebar digunakan untuk memperoleh luas persegi panjang. Karena hasil dari input() berupa teks, kedua nilai diubah menjadi bilangan bulat dengan int().
4. Setelah proses perhitungan selesai, nilai luas ditampilkan kepada pengguna melalui fungsi print()`.


### 2.2.5 Program "Konstanta_2611533005.py"

In [6]:
# Buat nama dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variable ditambah 4 digit nim terakhir contoh: jari_1234

from typing import Final, final
PI: Final = 3.14
print("pi: %f" % PI)
jari_3005 = float(input('Masukkan nilai jari-jari: '))
luas_3005 = PI * jari_3005 * jari_3005
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3005, luas_3005))

pi: 3.140000
Luas lingkaran dengan jari-jari 20.00 adalah 1256.00


**Penjelasan :**

1. Program diawali dengan mengambil Final dari modul typing, kemudian mendefinisikan nilai PI sebesar 3.14 sebagai konstanta.
2. Selanjutnya, program mencetak nilai PI menggunakan format angka desimal.
3. Program meminta pengguna untuk memasukkan jari-jari lingkaran. Nilai tersebut dikonversi ke tipe float dan disimpan pada variabel jari_3005.
4. Setelah mendapatkan nilai jari-jari, program menghitung luas lingkaran dengan memanfaatkan konstanta PI dan nilai jari_3005.
5. Pada bagian akhir, program menampilkan nilai jari-jari beserta hasil luas lingkaran dalam format dua angka di belakang koma.


---
# BAB III
# KESIMPULAN

Setelah menyelesaikan praktikum, dapat dipahami bahwa Python menyediakan beberapa tipe data dan konsep dasar yang dapat digunakan untuk membangun program sederhana. Tipe data yang dipelajari dalam praktikum meliputi integer, float, complex, string, dan boolean. Selain itu, digunakan pula variabel, operator perbandingan dan logika, percabangan `if`, serta fungsi `input()` dan `print()` untuk mengolah masukan dan menampilkan keluaran program.

Dari program-program yang telah dibuat, terlihat bahwa data yang diperoleh melalui `input()` harus disesuaikan dengan tipe data yang diperlukan sebelum digunakan dalam proses perhitungan. Praktikum juga memberikan contoh penerapan Python dalam perhitungan sederhana, seperti mencari luas persegi panjang dan luas lingkaran. Secara keseluruhan, praktikum ini memberikan pemahaman dasar mengenai penggunaan Python yang dapat menjadi bekal untuk mempelajari pembuatan program yang lebih kompleks.


---
## DAFTAR PUSTAKA

[1] Python Software Foundation. (2023). Python 3.11.9 documentation.

[2] Microsoft. (2024). Visual Studio Code Documentation. Diakses dari https://code.visualstudio.com/docs

[3] GitHub, Inc. (2024). GitHub Docs. Diakses dari https://docs.github.com